### ISSUE TITLE
Website Requirements

### ISSUE THREAD

**Issue by JamenMarz** [PoweredRails/PoweredRails#2]
# Website
So, we've been slacking a bit...  We can still do something for the website in terms of design, so I've made a list of things we can get done.

## TODO
- [ ] **Homepage**
  - [ ] Design
  - [ ] Backend
- [ ] **Docs / Wiki**
  - [ ] Design
  - [ ] Backend
- [ ] **API**
  - [ ] Backend

(Some additional / later on)
- [ ] **Page to promote web panels**
  - [ ] Design
- [ ] **Rails Developer Network**
  - [ ] Design
  - [ ] Backend

## Backend
- [ ] **NodeJS**
- [ ] **MongoDB / MySQL servers**
